name = "dr-brij-behari-dave"
main = "worker.js"  # Or the name of the file you created in Step 1
compatibility_date = "2024-01-01"

[assets]
directory = "./"  # Or the folder containing your static files (e.g., "dist", "public")
binding = "ASSETS"

[[r2_buckets]]
binding = "PAPERS_BUCKET"
bucket_name = "paper-uploads"